apartments/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'apartments'

urlpatterns = [
    # path('', views.apartments_list, name='list'),
    path('', views.ApartmentList.as_view(), name='list'),
    # path('<slug:apartment_name>', views.apartment_detail, name="detail")
    path('<int:apartment_id>', views.apartment_detail, name='detail'),
    path('available', views.available_apartments_list, name='available')
]

reservations/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'reservations'

urlpatterns = [
    # path('detail/', views.reservation_detail, name='detail'),
    path('reservation/', views.ReservationView.as_view(), name='reservation'),
    path('create/', views.create_reservation, name='create'),
    # path('<int:apartment_id>', views.apartment_detail, name='detail')
]

users/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

whproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', views.home, name='home'),
    path('', views.Home.as_view(), name='home'),
    path('apartments/', include('apartments.urls')),
    path('users/', include('users.urls')),
    path('reservations/', include('reservations.urls')),
    path('api/neighborhoods/', views.get_neighborhoods, name='get_neighborhoods'),
]

apartments/models.py
from django.db import models

# Create your models here.

class Apartment(models.Model):
    Name = models.CharField(max_length=200)
    Barrio = models.CharField(max_length=100)
    Ciudad = models.CharField(max_length=50)
    Pais = models.CharField(max_length=50)
    N_Personas = models.IntegerField(default=1)
    N_Banos =  models.IntegerField(default=1)
    N_Camas = models.IntegerField(default=1)
    ImagePath = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.Name

###

class ApartmentNew(models.Model):
    title = models.CharField(max_length=255)
    active = models.BooleanField(default=True)
    currency = models.CharField(max_length=10)
    base_price = models.DecimalField(max_digits=10, decimal_places=2)
    cleaning_fee = models.DecimalField(max_digits=10, decimal_places=2)
    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    neighborhood = models.CharField(max_length=100)
    bathrooms = models.IntegerField()
    accommodates = models.IntegerField()
    public_summary = models.TextField()

    class Meta:
        db_table = 'apartments_apartmentnew'
        verbose_name = "New apartment"
        verbose_name_plural = "New apartments"

    def __str__(self):
        return self.title
    
    @property
    def first_picture(self):
        first_pic = self.pictures.first()   
        return first_pic.url if first_pic else None
    
    @property
    def base_price_int(self):
        return int(self.base_price)


class ApartmentPicture(models.Model):
    apartment = models.ForeignKey(ApartmentNew, on_delete=models.CASCADE, related_name='pictures')
    url = models.URLField()

    class Meta:
        db_table = 'apartments_pictures'

    def __str__(self):
        return f"Picture for {self.apartment.title}"


class Room(models.Model):
    apartment = models.ForeignKey(ApartmentNew, on_delete=models.CASCADE, related_name='rooms')
    room_number = models.IntegerField()

    class Meta:
        db_table = 'apartments_rooms'

    def __str__(self):
        return f"Room {self.room_number} of {self.apartment.title}"


class Bed(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='beds')
    type = models.CharField(max_length=50)
    quantity = models.IntegerField()

    class Meta:
        db_table = 'apartments_beds'

    def __str__(self):
        return f"{self.quantity} x {self.type} in Room {self.room.room_number}"


class Amenity(models.Model):
    name = models.CharField(max_length=100, unique=True)

    class Meta:
        db_table = 'apartments_amenities'

    def __str__(self):
        return self.name


class ApartmentAmenity(models.Model):
    apartment = models.ForeignKey(ApartmentNew, on_delete=models.CASCADE, related_name='apartment_amenities')
    amenity = models.ForeignKey(Amenity, on_delete=models.CASCADE)

    class Meta:
        db_table = 'apartments_apartment_amenities'
        unique_together = ('apartment', 'amenity')

    def __str__(self):
        return f"{self.amenity.name} for {self.apartment.title}"
    
class ApartmentCountry(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        db_table = 'apartments_countries'

    def __str__(self):
        return self.name

class ApartmentCity(models.Model):
    country = models.ForeignKey(ApartmentCountry, on_delete=models.CASCADE, related_name='apartment_countries')
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'apartments_cities'

    def __str__(self):
        return self.name
    
class ApartmentNeighborhood(models.Model):
    city = models.ForeignKey(ApartmentCity, on_delete=models.CASCADE, related_name='apartment_neighborhoods')
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'apartments_neighborhoods'

    def __str__(self):
        return self.name

apartments/views.py
from django.db import connection
from django.shortcuts import get_object_or_404, render
from django.views import View
from django.db.models import Prefetch
from apartments.models import Apartment, ApartmentNew, ApartmentPicture
from reservations.models import ReservationNew
# from django.http import HttpResponse
from apartments.services import get_available_apartments

# Create your views here.

### Function Based Views ###

def apartments_list(request):
    apartments = Apartment.objects.all()
    return render(request, 'apartments_list.html', { 'apartments' : apartments })

def apartment_detail(request, apartment_id):
    # apartment = Apartment.objects.get(id=apartment_id)
    # apartment = ApartmentNew.objects.get(id=apartment_id)
    # return render(request, 'apartment_detail.html', { 'apartment' : apartment })
    apartment = get_object_or_404(ApartmentNew, id=apartment_id)
    pictures = list(apartment.pictures.order_by('id')[:3])  # force evaluate

    photo1 = pictures[0].url if len(pictures) > 0 else None
    photo2 = pictures[1].url if len(pictures) > 1 else None
    photo3 = pictures[2].url if len(pictures) > 2 else None

    context = {
        'apartment': apartment,
        'photo1': photo1,
        'photo2': photo2,
        'photo3': photo3
    }

    reponse = render(request, 'apartment_detail.html', context)

    print(len(connection.queries))
    return reponse
    # return render(request, 'apartment_detail.html', context)

def available_apartments_list(request):
    ciudad = request.GET.get('ciudad')
    distrito = request.GET.get('distrito')
    fecha_rango = request.GET.get('fecha_rango')
    adultos = request.GET.get('adultos')
    ninos = request.GET.get('ninos')
    mascotas = request.GET.get('mascotas')
    
    fechaSplit = fecha_rango.split("to")
    start_date = fechaSplit[0].replace(" ", "")
    end_date = fechaSplit[1].replace(" ", "")

    #print(start_date, end_date)

    apartments = get_available_apartments(start_date, end_date, ciudad, distrito)
    
    return render(request, 'apartments_list.html', {'apartments': apartments})

###

### Class Based Views ###

class ApartmentList(View):

    def get(self, request):
        apartments = self.get_filtered_apartments(request)
        context = {'apartments': apartments}
        reponse = render(request, 'apartments_list.html', context)

        print(len(connection.queries))
        return reponse

    def get_filtered_apartments(self, request):
        ciudad = request.GET.get('ciudad')
        barrio = request.GET.get('distrito')
        fecha_rango = request.GET.get('fecha_rango')
        adultos = request.GET.get('adultos')
        ninos = request.GET.get('ninos')

        apartments = ApartmentNew.objects.prefetch_related(
            Prefetch('pictures', queryset=ApartmentPicture.objects.order_by('id')),
            Prefetch('reservations_new', queryset=ReservationNew.objects.all())
        ).filter(active=True)
        # ).all()

        if ciudad and ciudad != 'All Cities':
            apartments = apartments.filter(city__iexact=ciudad)
        if barrio:
            apartments = apartments.filter(neighborhood__iexact=barrio)
        if adultos or ninos:
            apartments = apartments.filter(accommodates__gte=int(adultos)+int(ninos))

        if fecha_rango:
            start_date, end_date = [d.strip() for d in fecha_rango.split('to')]
            apartments = apartments.exclude(
                reservations_new__start_date__lt=end_date,
                reservations_new__end_date__gt=start_date
            )

        return apartments[:20]

apartments/templates/apartment_detail.html
{% extends "layout.html" %}

{% block title %}
    Detalle
{% endblock %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<div class="container my-5">
    <div class="row mb-4">
        <div class="col-lg-8">
            {% if photo1 %}
                <img src="{{ photo1 }}" class="img-fluid w-100 mb-2" alt="{{ apartment.Name }}" 
                style="height: 429px; display: block; object-fit: cover;">
            {% endif %}
        </div>
        <div class="col-lg-4 d-flex flex-column gap-2">
            {% if photo2 %}
                <img src="{{ photo2 }}" class="img-fluid" alt="Apartment photo 2" 
                style="height: 211px !important; display: block; object-fit: cover;">
            {% endif %}
            {% if photo3 %}
                <img src="{{ photo3 }}" class="img-fluid" alt="Apartment photo 3" 
                style="height: 211px !important; display: block; object-fit: cover;">
            {% endif %}
        </div>
    </div>
    
    <div class="row">
        <div class="col-lg-8">
            <div class="mb-4">
                {% comment %} <img src="{% static 'images/apartment-placeholder.jpg' %}" class="img-fluid w-100 mb-3" alt="{{ apartment.Name }}">
                <div class="d-flex gap-2">
                    <img src="{% static 'images/apartment-placeholder.jpg' %}" class="img-thumbnail" style="width: 100px;" alt="Thumbnail 1">
                    <img src="{% static 'images/apartment-placeholder.jpg' %}" class="img-thumbnail" style="width: 100px;" alt="Thumbnail 2">
                    <img src="{% static 'images/apartment-placeholder.jpg' %}" class="img-thumbnail" style="width: 100px;" alt="Thumbnail 3">
                </div> {% endcomment %}
            </div>
            <h2 class="fw-bold" style="text-transform: uppercase; font-size: 45px; margin-bottom: 0rem !important;">{{ apartment.title }}</h2>
            <p class="text-muted" style="margin-bottom: 0rem !important;">{{ apartment.neighborhood }}, {{ apartment.city }}, {{ apartment.country }}</p>
            <p style="margin-bottom: 0rem !important;">
                {{ apartment.accommodates }} invitados |
                1 habitación |
                {% comment %} {{ apartment.N_Camas }} cama(s) | {% endcomment %}
                {{ apartment.bathrooms }} baño(s)
            </p>
            <hr>
            <p>
                {{ apartment.public_summary }}
            </p>
            <hr>
            <h4 style="text-transform: uppercase; font-size: 30px;">Amenities</h4>
            <div class="row row-cols-2 row-cols-md-4 g-4">
                <div class="col text-center">
                    <img src="{% static 'images/elevator-svgrepo-com.svg' %}" alt="Elevator" class="amenity-icon">
                    <p>Elevator</p>
                </div>
                <div class="col text-center">
                    <img src="{% static 'images/parking-fee-svgrepo-com.svg' %}" alt="Indoor Parking" class="amenity-icon">
                    <p>Indoor Parking</p>
                </div>
                <div class="col text-center">
                    <img src="{% static 'images/tv-svgrepo-com.svg' %}" alt="TV" class="amenity-icon">
                    <p>TV</p>
                </div>
                <div class="col text-center">
                    <img src="{% static 'images/bell-boy-svgrepo-com.svg' %}" alt="Doorman" class="amenity-icon">
                    <p>Doorman</p>
                </div>
                <div class="col text-center">
                    <img src="{% static 'images/balcony-window-svgrepo-com.svg' %}" alt="Patio or Balcony" class="amenity-icon">
                    <p>Patio or Balcony</p>
                </div>
                <div class="col text-center">
                    <img src="{% static 'images/bbq-svgrepo-com.svg' %}" alt="BBQ Grill" class="amenity-icon">
                    <p>BBQ Grill</p>
                </div>
            </div>
            <hr>
            <h4 style="text-transform: uppercase; font-size: 30px;">Bedrooms</h4>
            <div class="row row-cols-2 row-cols-md-4 g-4">
                <div class="col text-center">
                    <img src="{% static 'images/bed-double-svgrepo-com.svg' %}" alt="Elevator" class="amenity-icon">
                    <p>1 Queen Bed</p>
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="border rounded p-4 shadow-sm">
                <div class="d-flex justify-content-between mb-3">
                    <span class="fw-bold">DIARIO</span>
                    <span>US$ 83.00 POR NOCHE</span>
                </div>
                <form action="{% url 'reservations:reservation' %}" method="get">
                    <input type="hidden" name="apartment_id" value="{{ apartment.id }}">
                    
                    <div class="mb-3">
                        <label for="dateRangeDetail" class="form-label">Llegada - Salida</label>
                        <input type="text" id="dateRangeDetail" name="date_range" class="form-control border-0 bg-transparent p-0" placeholder="Selecciona fechas" style="width: 220px; font-weight: bold;">
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Correo electrónico</label>
                        <input type="email" id="email" name="email" class="form-control" placeholder="tu@email.com">
                    </div>
                    <div class="mb-3">
                        <label for="phone" class="form-label">Teléfono</label>
                        <input type="tel" id="phone" name="phone" class="form-control" placeholder="+57">
                    </div>
                    <button type="submit" class="btn btn-dark w-100">RESERVAR AHORA</button>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const today = new Date();
        const tomorrow = new Date();
        tomorrow.setDate(today.getDate() + 1);
  
        flatpickr("#dateRangeDetail", {
            mode: "range",
            //dateFormat: "d M Y",
            dateFormat: "Y-m-d",
            minDate: "today",
            defaultDate: [today, tomorrow],
            onReady: function(selectedDates, dateStr, instance) {
              // Set the initial value once flatpickr is ready
              document.getElementById('inputFechaRango').value = dateStr;
            },
            onChange: function(selectedDates, dateStr) {
                document.getElementById('inputFechaRango').value = dateStr;
            }
        });
    });
</script>

{% endblock %}

apartments/templates/apartments_list.html
{% extends "layout.html" %}

{% block title %}
    Lista de Apartamentos
{% endblock %}

{% load static %}

{% block content %}
<div class="row">
    {% for apartment in apartments %}
    <div class="col-md-6 col-lg-4 mb-4">
        <a href="{% url 'apartments:detail' apartment_id=apartment.id %}" class="apartment-card">
            <div class="card h-100 border-0">
                {% comment %} <img src="{% static 'images/'|add:apartment.ImagePath %}" class="apartment-image" alt="Imagen de {{ apartment.Name }}"> {% endcomment %}
                <img src="{{ apartment.first_picture }}" class="apartment-image" alt="Imagen de {{ apartment.title }}">
                
                <div class="card-body" style="padding: 12px 0px 0px 0px !important">
                    <p class="card-title" style="font-weight: bold; font-size: 18px; margin-bottom: 0px;">{{ apartment.title }}</p>
                    <p class="card-text text-muted">
                        {{ apartment.neighborhood }}, {{ apartment.city }}, {{ apartment.country }}
                    </p>
                    <div class="d-flex justify-content-between align-items-center">
                        {% comment %} <span><strong>US$ 120</strong> / Noche</span> {% endcomment %}
                        <span>US$ {{ apartment.base_price_int }} / Noche</span>
                        <div>
                            <span class="me-3">
                                {{ apartment.accommodates }} <img src="{% static 'images/person-icon.svg' %}" style="padding-bottom: 3px;">
                            </span>
                            {% comment %} <span class="me-3">
                                <i class="bi bi-badge-wc"></i> {{ apartment.N_Banos }}
                            </span> {% endcomment %}
                            <span>
                                {{ apartment.bathrooms }} <img src="{% static 'images/bed-icon.svg' %}">
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {% empty %}
    <p>No hay apartamentos disponibles.</p>
    {% endfor %}
</div>
{% endblock %}